In [7]:
from numpy import random
print(random.randint(1,100))#random integer in the given range
print(random.rand())#float number 0-1

64
0.44976780058689614


In [8]:
#creating n dimensional array with random values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[57 77 95]
[[52 21 47 29]
 [78 31 27 56]
 [55 71 97 26]]
[[[13 45]
  [95 48]
  [56  6]
  [18 83]]

 [[14 26]
  [61 84]
  [85 96]
  [14 12]]

 [[16 64]
  [ 5 44]
  [69 54]
  [46 70]]]


In [9]:
#creating n dimensional array with random floating point values
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.9536687212100267
[0.86133275 0.24406524 0.86444113]
[[0.89899556 0.3838752  0.52947197]
 [0.38142731 0.42389886 0.63604136]]


In [10]:
a= random.randint(100,size=(3)).ravel()
a

array([ 2, 93, 83])

In [11]:
random.choice(a)

2

In [12]:
#for generating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size=(3,4))

array([[5, 1, 1, 3],
       [2, 2, 2, 3],
       [5, 4, 2, 2]])

### pandas :
1. Data manipulation,analysis and cleaning
2. tabular,unlabeled

In [16]:
import pandas as pd
import numpy as np
dict1 = {'a' :1,'b' :2,'c' :3,'d' :4,'e' :5}
dict2 = {'a' :5,'b' :6,'c' :7,'d' :8,'e' :9}
data = {"first":dict1,"second":dict2}
df = pd.DataFrame(data,dtype=np.int32)
df

first  second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [18]:
# simple dicionary-->dataframe
d1 = {"name":["pavan","phani","phanindra"],"address":["hyd","kurnool","goa"]}
df1 = pd.DataFrame(d1)
df1

name  address
0      pavan      hyd
1      phani  kurnool
2  phanindra      goa

In [21]:
# using series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([12.23,23.34,34.45,45.56,56.67,67.78,78.89,89.10,90.12,10.11])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"coloum1":s1,"coloum2":s2,"coloum3":s3}
df3 = pd.DataFrame(data)
df3

coloum1  coloum2 coloum3
0        1    12.23       a
1        2    23.34       b
2        3    34.45       c
3        4    45.56       d
4        5    56.67       e
5        6    67.78       f
6        7    78.89       g
7        8    89.10       h
8        9    90.12       i
9       10    10.11       j

### selecting the data from the data frame
. loc
. iloc

In [26]:
type(df3)

pandas.core.frame.DataFrame

In [27]:
df3["coloum2"]

0    12.23
1    23.34
2    34.45
3    45.56
4    56.67
5    67.78
6    78.89
7    89.10
8    90.12
9    10.11
Name: coloum2, dtype: float64

In [28]:
df3.iloc[0:4,0:1]

coloum1
0        1
1        2
2        3
3        4

In [31]:
df3.columns

Index(['coloum1', 'coloum2', 'coloum3'], dtype='object')

In [32]:
df3.head()

coloum1  coloum2 coloum3
0        1    12.23       a
1        2    23.34       b
2        3    34.45       c
3        4    45.56       d
4        5    56.67       e

In [34]:
df3.sample(2)

coloum1  coloum2 coloum3
1        2    23.34       b
3        4    45.56       d